trigger:
 branches:
   include:
   - main
 paths:
   include:
   - reports/*

variables:
  artifactName: '$(Build.DefinitionName)-$(Build.SourceVersion)'

pool:
  vmImage: 'windows-latest'

name: $(BuildDefinitionName).$(Year:yy)$(DayOfYear)$(rev:.r)

stages:
- stage: Build
  jobs:
  - job: power_bi_artifacts
    displayName: Create Artifacts for Power BI Reports
    steps:

    - task: PowerShell@2
      displayName: Copy Modified files to staging
      inputs:
        targetType: 'filePath'
        filePath: './pipelines/power-bi/templates/powershell/get-pbix-report.ps1'
        arguments: >
          -BuildSourcesDirectory $(Build.SourcesDirectory)
          -BuildArtifactStagingDirectory $(Build.ArtifactStagingDirectory)
      name: check_modified

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: $(artifactName)'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: $(artifactName)
        publishLocation: 'Container'

- stage: UAT
  dependsOn: Build
  condition: and(eq(dependencies.Build.outputs['power_bi_artifacts.check_modified.FilesChanged'], 'True'), succeeded('Build'))

  jobs:
  - template: /pipelines/power-bi/templates/power-bi-deployment.yml
    parameters:
      environment: UAT
      artifactName: $(artifactName)
      workspaceNameSuffix: '_UAT' # When no suffix is needed, remove the parameter or set it to the string 'null'.

- stage: Production
  dependsOn: UAT
  condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), succeeded('UAT'))

  jobs:
  - template: /pipelines/power-bi/templates/power-bi-deployment.yml
    parameters:
      environment: Production
      artifactName: $(artifactName)